<?php 
$spa = $context->isSpaMode();
$anchorStyle = ($spa) ? $context->getAnchorStyle() : 'classic';
?>

<!-- Display header on MPA mode -->
<?php if (!$spa) : ?>
	<?php 
	$this->current = 'orgUnit';
	echo $this->partial('/partials/menu'); 
	?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
<?php endif;?>

		<div class="panel panel-default">
            <div class="panel-heading">
				<?php echo $this->translate('Organization: delete', 'ppit-master-data', $context->getLocale());?>
 				<div class="btn-group pull-right">
					<?php echo $this->partial('/partials/anchor-widget.phtml', array(
							'glyphicon' => 'glyphicon-remove',
							'title' => $this->translate('Return to list', 'ppit-core', $context->getLocale()),
							'id' => 'remove-anchor',
							'anchorStyle' => $anchorStyle,
							'spa' => $spa,
					)) ?>
 				</div>
			</div>
           	<div class="panel-body">
				<table class="table-condensed">
					<tr>
						<td colspan="2">
<?php if ($orgUnit->child_type) : ?>
<!-- Add -->
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'glyphicon' => 'glyphicon-plus',
									'title' => $this->translate('Add', 'ppit-core', $context->getLocale()),
									'id' => 'add-anchor',
									'anchorStyle' => $anchorStyle,
									'spa' => $spa,
							)) ?>
<?php endif;?>

<!-- Update -->
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'glyphicon' => 'glyphicon-edit',
									'title' => $this->translate('Update', 'ppit-core', $context->getLocale()),
									'id' => 'update-anchor',
									'anchorStyle' => $anchorStyle,
									'spa' => $spa,
							)) ?>
						</td>
					</tr>
<?php if ($orgUnit->parent) : ?>
					<tr>
						<td class="ppit-header-caption"><?php echo $this->translate('Parent unit', 'ppit-master-data', $context->getLocale())?></td>
						<td><?php echo $orgUnit->parent->identifier.' - '.$orgUnit->parent->caption.' ('.$this->translate($orgUnit->parent->type, 'ppit-master-data', $context->getLocale()).')' ?>
					<tr>
<?php else : ?>
					<tr>
						<td class="ppit-header-caption"><?php echo $this->translate('Top level', 'ppit-master-data', $context->getLocale())?></td>
					<tr>
<?php endif;?>

				</table>
           	
<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
	'id' => $id,
	'update_time' => $orgUnit->update_time,
	'message' => $message,
	'error' => $error,
	'csrfForm' => $csrfForm,
	'context' => $context,
)) ?>

<!-- Form footer -->
<?php echo $this->partial('/partials/form-footer', array(
	'class' => 'btn-danger',
	'message' => $message,
	'context' => $context,
)) ?>

			</div>
		</div>

<?php if (!$context->isSpaMode()) : ?>
	</div>
</div>
<?php endif;?>

<script id='org_unit_delete_script'>

// Close form
<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'remove-anchor',
		'route' => $this->url('orgUnit/index', array('id' => ($orgUnit->parent) ? $orgUnit->parent->id : 0)),
		'spa' => $spa,
)) ?>

// Add
<?php echo $this->partial('/partials/show-form-script', array(
		'id' => 'add-anchor',
		'route' => $this->url('orgUnit/update', array('parent_id' => $id)),
		'script' =>'org_unit_update_script',
		'spa' => $spa,
)) ?>

// Update
<?php echo $this->partial('/partials/show-form-script', array(
		'id' => 'update-anchor',
		'route' => $this->url('orgUnit/update', array('parent_id' => 0, 'id' => $id)),
		'script' =>'org_unit_update_script',
		'spa' => $spa,
)) ?>

<?php if ($message == 'OK' || !$context->isAllowed('orgUnit/update')) : ?>

<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'foot-return-anchor',
		'route' => $this->url('orgUnit/index', array('id' => ($orgUnit->parent) ? $orgUnit->parent->id : 0)),
		'spa' => $spa,
)) ?>

<?php else : ?>

<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'cancel-anchor',
		'route' => $this->url('orgUnit/index', array('id' => ($orgUnit->parent) ? $orgUnit->parent->id : 0)),
		'spa' => $spa,
)) ?>

// Submit
<?php echo $this->partial('/partials/form-button-script', array(
		'context' => $context,
		'id' => 'submit-button',
		'formRoute' => $this->url('orgUnit/delete', array('id' => $id)),
		'formScript' =>'org_unit_delete_script',
		'properties' => array('update_time' => 'hidden'),
		'mainRoute' => $this->url('orgUnit/index'),
		'mainScript' =>'org_unit_index_script',
		'hideForm' => true,
)) ?>

<?php endif;?>

</script>

