<?php 
$spa = true;
$anchorStyle = ($spa) ? $context->getAnchorStyle() : 'classic';
$isDeletable = $orgUnit->isDeletable();
?>

<!-- Display header on MPA mode -->
<?php if (!$spa) : ?>
	<?php 
		$this->current = 'orgUnit';
		echo $this->partial('/partials/menu'); 
	?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
<?php endif;?>

		<div class="panel panel-default">
            <div class="panel-heading">
				<?php echo $this->translate('Organization: '.(($id) ? 'update' : 'add'), 'ppit-master-data', $context->getLocale()) ?>
 				<div class="btn-group pull-right">
					<?php echo $this->partial('/partials/anchor-widget.phtml', array(
							'glyphicon' => 'glyphicon-remove',
							'title' => $this->translate('Return to list', 'ppit-core', $context->getLocale()),
							'id' => 'remove-anchor',
							'anchorStyle' => $anchorStyle,
							'spa' => $spa,
					)) ?>
 				</div>
			</div>
           	<div class="panel-body">
				<table class="table-condensed">
					<tr>
						<td colspan="2">
<?php if ($orgUnit->child_type) : ?>
<!-- Add -->
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'glyphicon' => 'glyphicon-plus',
									'title' => $this->translate('Add', 'ppit-core', $context->getLocale()),
									'id' => 'add-anchor',
									'anchorStyle' => $anchorStyle,
									'spa' => $spa,
							)) ?>
<?php endif;?>

<?php if ($id) : ?>
<!-- Delete -->
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'glyphicon' => 'glyphicon-trash',
									'title' => $this->translate('Delete', 'ppit-core', $context->getLocale()),
									'id' => 'delete-anchor',
									'anchorStyle' => $anchorStyle,
									'class' => ($isDeletable) ? 'btn-danger' : 'btn-disabled',
									'disabled' => !$isDeletable,
									'spa' => $spa,
							)) ?>
<?php endif;?>
						</td>
					</tr>
<?php if ($orgUnit->parent) : ?>
					<tr>
						<td class="ppit-header-caption"><?php echo $this->translate('Parent unit', 'ppit-master-data', $context->getLocale())?></td>
						<td><?php echo $orgUnit->parent->identifier.' - '.$orgUnit->parent->caption.' ('.$this->translate($orgUnit->parent->type, 'ppit-master-data', $context->getLocale()).')' ?>
					<tr>
<?php else : ?>
					<tr>
						<td class="ppit-header-caption"><?php echo $this->translate('Top level', 'ppit-master-data', $context->getLocale())?></td>
					<tr>
<?php endif;?>

				</table>

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
			'id' => $id,
			'update_time' => $orgUnit->update_time,
			'message' => $message,
			'error' => $error,
			'csrfForm' => $csrfForm,
			'context' => $context,
)) ?>

<?php if ($message == 'OK' || !$context->isAllowed('orgUnit/update')) $isDisabled = true; else $isDisabled = false; ?>

<?php if (!$id && !$orgUnit->parent) : ?>
<!-- Types -->
	<div class="form-group">
		<label class="col-sm-6 control-label"><?php echo $this->translate('Choose applicable levels:', 'ppit-master-data', $context->getLocale()) ?></label>
	</div>

	<?php foreach ($orgUnit->types as $type) : ?>
		<?php
			echo $this->partial('/partials/checkbox-widget.phtml', array(
				'property' => 'type_'.$type,
				'label' => $this->translate($type, 'ppit-master-data', $context->getLocale()),
				'value' => 0,
				'context' => $context,
				'isDisabled' => $isDisabled,
		)); ?>
	<?php endforeach;?>

	<div class="form-group"><label class="col-sm-6 control-label">&nbsp;</label></div>
	
<?php else : ?>
<!-- Type -->

	<?php
		echo $this->partial('/partials/input-widget.phtml', array(
			'property' => 'type',
			'label' => $this->translate('Type', 'ppit-core', $context->getLocale()),
			'value' => $orgUnit->type, //$this->translate($orgUnit->type, 'ppit-master-data', $context->getLocale()),
			'isMandatory' => true,
			'maxLength' => 255,
			'context' => $context,
			'isDisabled' => true,
	)); ?>
<?php endif;?>
	
<!-- Identifier -->

<?php
	echo $this->partial('/partials/input-widget.phtml', array(
		'property' => 'identifier',
		'label' => '* '.$this->translate('Identifier', 'ppit-core', $context->getLocale()),
		'value' => $orgUnit->identifier,
		'isMandatory' => true,
		'maxLength' => 255,
		'context' => $context,
		'isDisabled' => $isDisabled,
)); ?>

<!-- Caption -->

<?php
	echo $this->partial('/partials/input-widget.phtml', array(
		'property' => 'caption',
		'label' => '* '.$this->translate('Caption', 'ppit-core', $context->getLocale()),
		'value' => $orgUnit->caption,
		'isMandatory' => true,
		'maxLength' => 255,
		'context' => $context,
		'isDisabled' => $isDisabled,
)); ?>
					
<!-- Description -->
<?php echo $this->partial('/partials/textarea-widget.phtml', array(
		'property' => 'description',
		'label' => $this->translate('Description', 'ppit-core', $context->getLocale()),
		'rows' => 3, 
		'value' => $orgUnit->description,
		'isMandatory' => false,
		'maxLength' => 2047,
		'context' => $context,
		'isDisabled' => $isDisabled,
)); ?>

<!-- Place of businesss -->
<?php
	echo $this->partial('/partials/input-widget.phtml', array(
		'property' => 'place_identifier',
		'label' => $this->translate('Place of business', 'ppit-master-data', $context->getLocale()),
		'value' => ($orgUnit->place_id) ? $orgUnit->place_identifier.' - '.$orgUnit->place_name : '',
		'isMandatory' => false,
		'context' => $context,
		'isDisabled' => $isDisabled,
)); ?>
<input type="hidden" id="place_id" name="place_id" />

<!-- Open -->
<?php
	echo $this->partial('/partials/checkbox-widget.phtml', array(
		'property' => 'is_open',
		'label' => $this->translate('Open ?', 'ppit-master-data', $context->getLocale()),
		'value' => $orgUnit->is_open,
		'context' => $context,
		'isDisabled' => $isDisabled,
)); ?>
	
<!-- Form footer -->
<?php echo $this->partial('/partials/form-footer') ?>

<!-- Authorization section -->
				<div id="org_unit_contact_list"></div>

			</div>
		</div>
<?php if (!$spa) : ?>
	</div>
</div>
<?php endif;?>

<script id='org_unit_update_script'>

$('#place_identifier').autocomplete({
	source : function(request, response){
    $.ajax({
    		url : '<?php echo $this->url('place/dataList') ?>', // Server request returning json data
            dataType : 'json', // The data type is json
            data : {
                identifier : $('#place_identifier').val(), // Giving the prefix (at least 3 chars input)
                maxRows : 15
            },
            
            success : function(donnee){
	            response($.map(donnee.data, function(object){
	        		document.getElementById("place_id").value = object.id;
		            return object.identifier + ' - ' + object.name;
        	    }));
            }
        });
    }
});

// Close form
<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'remove-anchor',
		'route' => $this->url('orgUnit/index', array('id' => ($orgUnit->parent) ? $orgUnit->parent->id : 0)),
		'spa' => $spa,
)) ?>

// Add
<?php echo $this->partial('/partials/show-form-script', array(
		'id' => 'add-anchor',
		'route' => $this->url('orgUnit/update', array('parent_id' => $id)),
		'script' =>'org_unit_update_script',
		'spa' => $spa,
)) ?>

// Delete
<?php echo $this->partial('/partials/show-form-script', array(
		'id' => 'delete-anchor',
		'route' => $this->url('orgUnit/delete', array('id' => $id)),
		'script' =>'org_unit_delete_script',
		'spa' => $spa,
)) ?>

<?php if ($message == 'OK') : ?>

<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'foot-return-anchor',
		'route' => $this->url('orgUnit/index', array('id' => ($orgUnit->parent) ? $orgUnit->parent->id : 0)),
		'spa' => $spa,
)) ?>

<?php else : ?>

<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'cancel-anchor',
		'route' => $this->url('orgUnit/index', array('id' => ($orgUnit->parent) ? $orgUnit->parent->id : 0)),
		'spa' => $spa,
)) ?>

// Submit
<?php
$properties = array('identifier' => 'input', 'caption' => 'input', 'description' => 'input', 'place_id' => 'hidden', 'is_open' => 'checkbox', 'update_time' => 'hidden');
if (!$id && !$orgUnit->parent) {
	foreach ($orgUnit->types as $type) $properties['type_'.$type] = 'checkbox';
}
echo $this->partial('/partials/form-button-script', array(
		'context' => $context,
		'id' => 'submit-button',
		'formRoute' => $this->url('orgUnit/update', array('parent_id' => ($orgUnit->parent) ? $orgUnit->parent->id : 0, 'id' => $id)),
		'formScript' => 'org_unit_update_script',
		'properties' => $properties,
		'mainRoute' => $this->url('orgUnit/index'),
		'mainScript' =>'org_unit_index_script',
		'hideForm' => false,
)) ?>

<?php endif;?>

<?php if ($id) : ?>
	
	// Authorization section
	function getOrgUnitContactList() {
		var xhttp = new XMLHttpRequest();
		xhttp.onreadystatechange = function() {
			if (xhttp.readyState == 4 && xhttp.status == 200) {
				document.getElementById('org_unit_contact_list').innerHTML = xhttp.responseText;
	<?php if ($config['ppitCoreSettings']['isTraceActive']) : ?>
				console.log('getOrgUnitContactList, route = ' + '<?php echo $this->url('orgUnitContact/list', array('org_unit_id' => $orgUnit->id)) ?>');
				console.log(xhttp.responseText);
	<?php endif;?>
				eval(document.getElementById('org_unit_contact_list_script').innerHTML);
			}
		}
		xhttp.open('GET', '<?php echo $this->url('orgUnitContact/list', array('org_unit_id' => $orgUnit->id)) ?>', true);
		xhttp.send();
	}
	
	getOrgUnitContactList();

<?php endif;?>

</script>
