<?php
	$title = $this->translate('Catalogue: Product options', 'ppit-master-data', $context->getLocale());
    echo $this->partial('/partials/menu');
?>
<?php $this->headTitle($title); ?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
		<div class="panel panel-default">
            <div class="panel-heading">
				<strong><?php echo $this->translate('Add an option', 'ppit-master-data', $context->getLocale());?></strong>
            </div>
           	<div class="panel-body">
				<table class="table-condensed">
					<tr>
						<td align="right"><strong><?php echo $this->translate('Product', 'ppit-master-data', $context->getLocale()) ?></strong></td>
						<td><?php echo $product->brand.' - '.$product->model ?></td>
					</tr>
					<tr><td colspan="2">&nbsp;</td></tr>
				</table>

<!-- Form opening tag -->
				<form action="<?php echo $this->url('productOption/add', array('id' => $id)) ?>" method="post" name="productOption" class="form-horizontal" enctype="form-data" id="productOption" onSubmit="return checkForm()">

<!--  CSRF -->
<?php $element = $csrfForm->get('csrf') ?>
				    <div class="form-group">
						<?php echo $this->formElement($element) ?>
<?php if ($this->formElementErrors($element)) : ?>
						<div class="col-sm-12"><p class="help-block"><?php echo $this->translate('The form has expired, please input again', 'ppit-core', $context->getLocale()) ?></p></div>
<?php endif;?>
					</div>

<!--  Duplicate error -->
<?php if ($error == 'Duplicate') : ?>
				    <div class="form-group">
						<div class="col-sm-12"><p class="help-block"><?php echo $this->translate('An option with the same reference on the same product already exists', 'ppit-master-data', $context->getLocale()) ?></p></div>
					</div>
<?php endif;?>

<!-- Reference -->
				    <div class="form-group" id="reference_group">
						<label class="col-sm-4 control-label">* <?php echo $this->translate('Reference', 'ppit-core', $context->getLocale()) ?></label>
						<div class="col-sm-8">
							<input  name="reference" id="reference" class="form-control" value="<?php echo $productOption->reference ?>">
						</div>
						<div class="col-sm-12"><p class="help-block" id="reference_error"></p></div>
					</div>

<!-- Caption -->
				    <div class="form-group" id="caption_group">
						<label class="col-sm-4 control-label">* <?php echo $this->translate('Caption', 'ppit-core', $context->getLocale()) ?></label>
						<div class="col-sm-8">
							<input  name="caption" id="caption" class="form-control" value="<?php echo $productOption->caption ?>">
						</div>
						<div class="col-sm-12"><p class="help-block" id="caption_error"></p></div>
					</div>
					
<!-- Description -->
					<div class="form-group" id="description_group">
						<label class="col-sm-4 control-label"><?php echo $this->translate('Description', 'ppit-core', $context->getLocale()) ?></label>
						<div class="col-sm-8">
							<textarea name="description" rows="3" cols="100" id="description" class="form-control"><?php echo $productOption->description ?></textarea>
						</div>
						<div class="col-sm-12"><p class="help-block" id="description_error"></p></div>
					</div>
					
<!-- Available ? -->
					<div class="form-group">
						<label class="col-sm-4 control-label"><?php echo $this->translate('Available ?', 'ppit-core', $context->getLocale()) ?></label>
						<div class="col-sm-8">
							<input type="checkbox" name="is_available" id="is_available" class="form-control" value="1" <?php if ($productOption->is_available) echo 'checked="checked"' ?>>
						</div>
					</div>

<!-- Submit button -->
				    <div class="form-group">
						<div class="col-sm-4">&nbsp;</div>
						<div class="col-sm-8">
							<input name="submit" type="submit" id="submitbutton" class="btn btn-primary" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
							&nbsp;&nbsp;
							<a href="<?php echo $this->url('productOption/index', array('id' => $product->id)) ?>"><?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?></a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<!-- Load the common form javascript functions -->
<?php echo $this->partial('/partials/common-form-js.phtml'); ?>

<script>

// The elements are checked last to first so the focus is positionned on the first element on error
function checkForm() 
{
	var validity = true;	
	
	// Description
	if (document.getElementById("description").value > 2047) {
    	renderElement("description", "<?php echo $this->translate('The input is too long', 'ppit-core', $context->getLocale()) ?>");
    	validity = false;
    }
    else {
    	renderElement("description", null);
	}
	
	// Caption
	if (document.getElementById("caption").value == "") {
		renderElement("caption", "<?php echo $this->translate('Please input a value', 'ppit-core', $context->getLocale()) ?>");
		validity = false;
	}
    else if (document.getElementById("caption").value > 255) {
    	renderElement("caption", "<?php echo $this->translate('The input is too long', 'ppit-core', $context->getLocale()) ?>");
    	validity = false;
    }
    else {
    	renderElement("caption", null);
	}
	
	// Reference
	if (document.getElementById("reference").value == "") {
		renderElement("reference", "<?php echo $this->translate('Please input a value', 'ppit-core', $context->getLocale()) ?>");
		validity = false;
	}
    else if (document.getElementById("reference").value > 255) {
    	renderElement("reference", "<?php echo $this->translate('The input is too long', 'ppit-core', $context->getLocale()) ?>");
    	validity = false;
    }
    else {
    	renderElement("reference", null);
	}
	
	return validity;
}
</script>
  