<?php 
$spa = true;
$anchorStyle = ($spa) ? $context->getAnchorStyle() : 'classic';
?>

<!-- Display header on MPA mode -->
<?php if (!$spa) : ?>
	<?php 
	$this->current = 'product';
	echo $this->partial('/partials/menu'); 
	?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
<?php endif;?>

		<div class="panel panel-default">
            <div class="panel-heading">
				<?php echo $this->translate('Delete an option', 'ppit-master-data', $context->getLocale());?>
 				<div class="btn-group pull-right">
					<?php echo $this->partial('/partials/anchor-widget.phtml', array(
							'glyphicon' => 'glyphicon-remove',
							'title' => $this->translate('Return to list', 'ppit-core', $context->getLocale()),
							'id' => 'remove-anchor',
							'anchorStyle' => $anchorStyle,
							'spa' => $spa,
					)) ?>
 				</div>
			</div>
           	<div class="panel-body">
           		<table class="table-condensed">
					<tr>
						<td align="right"><strong><?php echo $this->translate('Product', 'ppit-master-data', $context->getLocale()) ?></strong></td>
						<td><?php echo $productOption->product->brand.' - '.$productOption->product->model ?></td>
					</tr>
           			<tr>
						<td align="right"><strong><?php echo $this->translate('Option', 'ppit-master-data', $context->getLocale()) ?></strong></td>
						<td><?php echo $productOption->reference.' - '.$productOption->caption ?></td>
					</tr>
				</table>

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
	'id' => $id,
	'update_time' => $productOption->update_time,
	'message' => $message,
	'error' => $error,
	'csrfForm' => $csrfForm,
	'context' => $context,
)) ?>

<!-- Form footer -->
<?php echo $this->partial('/partials/form-footer', array(
	'class' => 'btn-danger',
	'message' => $message,
	'context' => $context,
)) ?>

			</div>
		</div>

<script id='product_option_delete_script'>

// Close form
<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'remove-anchor',
		'route' => $this->url('productOption/index', array('product_id' => $productOption->product_id)),
		'spa' => $spa,
)) ?>

<?php if ($message == 'OK') : ?>

<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'foot-return-anchor',
		'route' => $this->url('productOption/index', array('product_id' => $productOption->product_id)),
		'spa' => $spa,
)) ?>

<?php else : ?>

<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'cancel-anchor',
		'route' => $this->url('productOption/index', array('product_id' => $productOption->product_id)),
		'spa' => $spa,
)) ?>

// Submit
<?php echo $this->partial('/partials/form-button-script', array(
		'context' => $context,
		'id' => 'submit-button',
		'checkFunction' => 'checkForm',
		'formRoute' => $this->url('productOption/delete', array('id' => $id)),
		'formScript' =>'product_option_delete_script',
		'properties' => array('update_time' => 'hidden'),
		'mainRoute' => $this->url('productOption/index', array('product_id' => $productOption->product_id)),
		'mainScript' =>'product_script',
		'hideForm' => true,
)) ?>

<?php endif;?>

function checkForm() 
{
	return true;
}

</script>
