	<?php
$spa = true;
$anchorStyle = ($spa) ? $context->getAnchorStyle() : 'classic';
$current = 'product';
?>

<!-- Display header on MPA mode -->
<?php if (!$spa) : ?>
	<?php 
		$this->current = 'product';
		echo $this->partial('/partials/menu'); 
	?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
<?php endif;?>

		<div class="panel panel-default">
            <div class="panel-heading">
				<?php echo $this->translate('Options', 'ppit-master-data', $context->getLocale()) ?>: <?php echo $product->brand.' - '.$product->caption ?>
            </div>
		    <div class="panel-body">
				<table class="table-condensed">
					<tr>
						<td>
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'text' => $this->translate('Return to products', 'ppit-master-data', $context->getLocale()),
									'id' => 'product-anchor',
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
							)) ?>
						</td>
					</tr>
				</table>
		    	<table class="table table-striped">
					<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
						<th>&nbsp;</th>
						<th>&nbsp;</th>
						<th>
							<?php echo $this->translate('Reference', 'ppit-core', $context->getLocale());?>
						</th>
						<th>
							<?php echo $this->translate('Caption', 'ppit-core', $context->getLocale());?>
						</th>
					</tr>
					<tr>
						<td colspan="16">
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'glyphicon' => 'glyphicon-plus',
									'title' => $this->translate('Add', 'ppit-core', $context->getLocale()),
									'id' => 'add-anchor',
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
							)) ?>
						</td>
					</tr>
<?php foreach ($productOptions as $productOption) : ?>
					<tr<?php if (!$productOption->is_available) echo ' class="inactive"'?>>
			
<!-- Update or detail -->
						<td>
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'glyphicon' => 'glyphicon-edit',
									'title' => $this->translate('Update', 'ppit-core', $context->getLocale()),
									'id' => 'update-anchor-'.$productOption->id,
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
							)) ?>
						</td>
					
<!-- Delete -->
						<td>
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'glyphicon' => 'glyphicon-trash',
									'title' => $this->translate('Delete', 'ppit-core', $context->getLocale()),
									'id' => 'delete-anchor-'.$productOption->id,
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
									'disabled' => !$product->isDeletable(),
							)) ?>
						</td>

						<td><?php echo $productOption->reference ?></td>
						<td><?php echo $productOption->caption ?></td>

					</tr>
<?php endforeach; ?>
				</table>

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
			'update_time' => $product->update_time,
			'message' => $message,
			'error' => $error,
			'csrfForm' => $csrfForm,
			'context' => $context,
)) ?>

<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>
	
					<table class="table-condensed">
					
<!--  Dependance matrix -->
						<tr><td colspan="2"><strong><?php echo $this->translate('Dependence matrix', 'ppit-master-data', $context->getLocale()) ?></strong></td></tr>
					</table>
					
					<table class="table">
						<tr>
							<td>&nbsp;</td>
<?php $rowNum = 0; foreach ($matrix as $row_id => $row) : ?>
	<?php $rowNum++; ?>
							<td align="center"><?php echo '('.$rowNum.')' ?></td>
<?php endforeach; ?>
						</tr>

<?php $rowNum = 0; foreach ($matrix as $row_id => $row) : ?>
						<tr>
	<?php $rowNum++; $option = $productOptionTable->get($row_id); ?>
							<td><?php echo $option->caption.' ('.$rowNum.')' ?></td>
	<?php foreach ($row as $col_id => $constraint) : ?>
		<?php if ($row_id == $col_id) : ?>
							<td>&nbsp;</td>
		<?php else : ?>
							<td align="center">
								<input 	type="checkbox" name="<?php echo 'dep_'.$row_id.'_'.$col_id ?>" id="<?php echo 'dep_'.$row_id.'_'.$col_id ?>"
										class="form-control" value="1"
										<?php if ($constraint == 1) echo 'checked="checked"';?>>
							</td>
		<?php endif; ?>
	<?php endforeach;?>
						</tr>
<?php endforeach; ?>

						<tr><td colspan="<?php echo $rowNum+1?>">&nbsp;</td></tr>
					</table>
						
<!--  Exclusion matrix -->
					<table class="table-condensed">
						<tr><td colspan="2"><strong><?php echo $this->translate('Exclusion matrix', 'ppit-master-data', $context->getLocale()) ?></strong></td></tr>
					</table>

					<table class="table">
						<tr>
							<td>&nbsp;</td>
<?php $rowNum = 0; foreach ($matrix as $row_id => $row) : ?>
	<?php $rowNum++; ?>
							<td align="center"><?php echo '('.$rowNum.')' ?></td>
<?php endforeach; ?>
						</tr>

<?php $rowNum = 0; foreach ($matrix as $row_id => $row) : ?>
						<tr>
	<?php $rowNum++; $option = $productOptionTable->get($row_id); ?>
							<td><?php echo $option->caption.' ('.$rowNum.')' ?></td>
	<?php foreach ($row as $col_id => $constraint) : ?>
		<?php if ($row_id == $col_id) : ?>
							<td>&nbsp;</td>
		<?php else : ?>
							<td align="center">
								<input 	type="checkbox" name="<?php echo 'exc_'.$row_id.'_'.$col_id ?>" id="<?php echo 'exc_'.$row_id.'_'.$col_id ?>"
										class="form-control" value="1"
										<?php if ($constraint == 2) echo 'checked="checked"';?>>
							</td>
		<?php endif; ?>
	<?php endforeach;?>
						</tr>
<?php endforeach; ?>
					</table>

<!-- Submit button -->
				    <div class="form-group" id="submit-group">
						<div class="col-sm-4">&nbsp;</div>
						<div class="col-sm-8">
<?php if (!isset($class)) $class = 'btn-warning'; ?>
							<input name="submit" type="submit" id="submit-button" class="btn <?php echo $class ?>" value="<?php echo $this->translate('Confirm the update', 'ppit-core', $context->getLocale()) ?>">
						</div>
					</div>
					
			</div>
		</div>
<?php if (!$spa) : ?>
	</div>
</div>
<?php endif;?>
		
<script id='product_option_script'>

// Dependencies
<?php foreach ($matrix as $row_id => $row) : ?>
	<?php foreach ($row as $col_id => $constraint) : ?>
		<?php if ($row_id != $col_id) : ?>
function update_dep_<?php echo $row_id ?>_<?php echo $col_id ?>() {
	$('#submit-group').show();
	if (document.getElementById("dep_<?php echo $row_id ?>_<?php echo $col_id ?>").checked) {
		document.getElementById("dep_<?php echo $col_id ?>_<?php echo $row_id ?>").checked = false;
		document.getElementById("exc_<?php echo $row_id ?>_<?php echo $col_id ?>").checked = false;
		document.getElementById("exc_<?php echo $col_id ?>_<?php echo $row_id ?>").checked = false;
	}
}
$('#dep_<?php echo $row_id.'_'.$col_id ?>').change(update_dep_<?php echo $row_id.'_'.$col_id ?>);

// Exclusions
function update_exc_<?php echo $row_id ?>_<?php echo $col_id ?>() {
	$('#submit-group').show();
	if (document.getElementById("exc_<?php echo $row_id ?>_<?php echo $col_id ?>").checked) {
		document.getElementById("exc_<?php echo $col_id ?>_<?php echo $row_id ?>").checked = true;
		document.getElementById("dep_<?php echo $row_id ?>_<?php echo $col_id ?>").checked = false;
		document.getElementById("dep_<?php echo $col_id ?>_<?php echo $row_id ?>").checked = false;
	}
	else if (!document.getElementById("exc_<?php echo $row_id ?>_<?php echo $col_id ?>").checked) {
		document.getElementById("exc_<?php echo $col_id ?>_<?php echo $row_id ?>").checked = false;
	}
}
$('#exc_<?php echo $row_id.'_'.$col_id ?>').change(update_exc_<?php echo $row_id.'_'.$col_id ?>);

		<?php endif;?>
	<?php endforeach;?>
<?php endforeach;?>

$('#submit-group').hide();

// Product category
<?php echo $this->partial('/partials/show-main-script', array(
		'id' => 'product-anchor',
		'route' => $this->url('product/index'),
		'script' =>'product_script',
		'hideForm' => true,
		'spa' => $spa,
)) ?>

// Add
<?php echo $this->partial('/partials/show-form-script', array(
		'id' => 'add-anchor',
		'route' => $this->url('productOption/update', array('product_id' => $product->id)),
		'script' =>'product_option_update_script',
		'spa' => $spa,
)) ?>

<?php foreach ($productOptions as $productOption) : ?>

// Update
	<?php echo $this->partial('/partials/show-form-script', array(
			'id' => 'update-anchor-'.$productOption->id,
			'route' => $this->url('productOption/update', array('product_id' => $product->id, 'id' => $productOption->id)),
			'script' =>'product_option_update_script',
			'spa' => $spa,
	)) ?>
	
// Delete
	<?php echo $this->partial('/partials/show-form-script', array(
			'id' => 'delete-anchor-'.$productOption->id,
			'route' => $this->url('productOption/delete', array('id' => $productOption->id)),
			'script' =>'product_option_delete_script',
			'spa' => $spa,
	)) ?>

<?php endforeach;?>

// Submit
<?php
$properties = array(
		'update_time' => 'hidden',
);
// Dependencies
foreach ($matrix as $row_id => $row) {
	foreach ($row as $col_id => $constraint) {
		if ($row_id != $col_id) {
			$properties['#dep_'.$row_id.'_'.$col_id] = 'checkbox';
			$properties['#exc_'.$row_id.'_'.$col_id] = 'checkbox';
		}
	}
}

echo $this->partial('/partials/form-button-script', array(
		'context' => $context,
		'id' => 'submit-button',
		'checkFunction' => 'checkForm',
		'formRoute' => $this->url('productOption/index', array('product_id' => $product_id)),
		'formScript' =>'product_option_script',
		'properties' => $properties,
		'mainRoute' => $this->url('productOption/index', array('product_id' => $product_id)),
		'mainScript' =>'product_option_script',
		'hideForm' => false,
)) ?>

// The elements are checked last to first so the focus is positionned on the first element on error
function checkForm() { return true; }

</script>
