<!-- Load the common form javascript functions -->
<?php echo $this->partial('/partials/common-form-js.phtml'); ?>

<?php
$title = $context->getConfig('ppitProduct/index')['title'][$context->getLocale()];
$this->headTitle($title);
echo $this->partial('/partials/header');
?>

<div class="container">
	
	<div>&nbsp;</div>
	
	<div id="main_menu" >
	    <div class="col-md-10 col-md-offset-1">
			<div align="center">

	<?php if ($context->isAllowed('commitmentAccount/index')) : ?>
				<button type="button" class="btn btn-default menu-btn" id="account-anchor">
					<span class="glyphicon glyphicon-user"></span>
					<?php echo $this->translate('Accounts', 'ppit-commitment', $context->getLocale()) ?>
				</button>
	<?php endif ?>

<?php foreach ($types as $typeId => $typeDef) : ?>
	<?php if ($context->isAllowed('commitment/index')) : ?>
				<button type="button" class="btn btn-default menu-btn" id="commitment-<?php echo $typeId ?>-anchor">
					<?php echo $typeDef['labels'][$context->getLocale()] ?>
				</button>
	<?php endif ?>
<?php endforeach ?>

	<?php if ($context->isAllowed('commitmentTerm/index')) : ?>
				<button type="button" class="btn btn-default menu-btn" id="term-anchor">
					<span class="glyphicon glyphicon-calendar"></span>
					<?php echo $this->translate('Terms', 'ppit-commitment', $context->getLocale()) ?>
				</button>
	<?php endif ?>

<?php foreach ($types as $typeId => $typeDef) : ?>
	<?php if ($context->isAllowed('product/index')) : ?>
				<button type="button" class="btn btn-default menu-btn" id="product-anchor">
					<span class="glyphicon glyphicon-book"></span>
					<?php echo $this->translate('Catalogue', 'ppit-master-data', $context->getLocale()) ?>
				</button>
	<?php endif ?>
<?php endforeach ?>

	<?php if ($context->isAllowed('commitmentMessage/index')) : ?>
				<button type="button" class="btn btn-default menu-btn" id="message-anchor">
					<span class="glyphicon glyphicon-transfer"></span>
					<?php echo $this->translate('Interactions', 'ppit-commitment', $context->getLocale()) ?>
				</button>
	<?php endif ?>

			</div>
			<div>&nbsp;</div>
		</div>
	</div>

	<!-- Main panel -->
	<div class="row">
	    <div class="col-md-6 ppit-panel" id="search_panel"></div>
		<div class="col-md-6 ppit-panel" id="form_panel"></div>
	</div>
	
	<!-- Login -->
	<div class="row">
	    <div class="col-md-6 col-md-offset-3 ppit-panel" id="login-panel">
		</div>
	</div>
</div>

<script>

<?php echo $this->partial('/partials/product-scripts') ?>
<?php echo $this->partial('/partials/option-scripts') ?>
<?php echo $this->partial('/partials/ppit-controller') ?>

$('#account-anchor').click(function () { $(location).attr('href', '<?php echo $this->url('commitmentAccount/index', array('type' => $typeId)) ?>'); });
<?php foreach ($types as $typeId => $unused) : ?>
$('#commitment-<?php echo $typeId ?>-anchor').click(function () { $(location).attr('href', '<?php echo $this->url('commitment/index', array('type' => $typeId)) ?>'); });
$('#product-anchor').click(function () { $(location).attr('href', '<?php echo $this->url('product/index', array('type' => $typeId)) ?>'); });
<?php endforeach;?>
$('#term-anchor').click(function () { $(location).attr('href', '<?php echo $this->url('commitmentTerm/index') ?>'); });
$('#message-anchor').click(function () { $(location).attr('href', '<?php echo $this->url('commitmentMessage/index') ?>'); });

activateProduct('<?php echo $type ?>');

</script>
