<?php
$spa = $context->isSpaMode();
$anchorStyle = ($spa) ? $context->getAnchorStyle() : 'classic';
$current = 'product';
?>

<!-- Display header on MPA mode -->
<?php if (!$spa) : ?>
	<?php 
		$this->current = 'product';
		echo $this->partial('/partials/menu'); 
	?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
<?php endif;?>

		<div class="panel panel-default">
            <div class="panel-heading">
				<?php echo $this->translate('Products', 'ppit-master-data', $context->getLocale()) ?>: <?php echo $productCategory->caption ?>
            </div>
		    <div class="panel-body">
				<table class="table-condensed">
					<tr>
						<td>
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'text' => $this->translate('Product categories', 'ppit-master-data', $context->getLocale()),
									'id' => 'product-category-anchor',
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
							)) ?>
						</td>
					</tr>
				</table>
		    	<table class="table table-striped">
					<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
						<td colspan="3">&nbsp;</td>
						<td><strong>
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'text' => $this->translate('Brand', 'ppit-master-data', $context->getLocale()),
									'id' => 'brand-anchor',
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
							)) ?>
						</strong></td>
						<td><strong>
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'text' => $this->translate('Reference', 'ppit-master-data', $context->getLocale()),
									'id' => 'reference-anchor',
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
							)) ?>
						</strong></td>
						<td><strong>
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'text' => $this->translate('Caption', 'ppit-master-data', $context->getLocale()),
									'id' => 'caption-anchor',
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
							)) ?>
						</strong></td>
					</tr>
<?php if ($context->isAllowed('product/update')) : ?>
					<tr>
						<td colspan="16">
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'glyphicon' => 'glyphicon-plus',
									'title' => $this->translate('Add', 'ppit-core', $context->getLocale()),
									'id' => 'add-anchor',
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
							)) ?>
						</td>
					</tr>
<?php endif;?>

<?php foreach ($products as $product) : ?>
					<tr<?php if (!$product->is_available) echo ' class="inactive"'?>>
					
<!-- Update or detail -->
	<?php if ($context->isAllowed('product/update')) : ?>
						<td>
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'glyphicon' => 'glyphicon-edit',
									'title' => $this->translate('Update', 'ppit-core', $context->getLocale()),
									'id' => 'update-anchor-'.$product->id,
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
							)) ?>
						</td>
	<?php else : ?>
						<td>
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'glyphicon' => 'glyphicon-zoom-in',
									'title' => $this->translate('Detail', 'ppit-core', $context->getLocale()),
									'id' => 'detail-anchor-'.$product->id,
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
							)) ?>
						</td>
	<?php endif; ?>
					
<!-- Delete -->
	<?php if ($context->isAllowed('product/delete')) : ?>
						<td>
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'glyphicon' => 'glyphicon-trash',
									'title' => $this->translate('Delete', 'ppit-core', $context->getLocale()),
									'id' => 'delete-anchor-'.$product->id,
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
									'disabled' => !$product->isDeletable(),
							)) ?>
						</td>
	<?php else : ?>
						<td>&nbsp;</td>
	<?php endif; ?>
	
						<td>
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'text' => $this->translate('Options', 'ppit-master-data', $context->getLocale()),
									'id' => 'option-anchor-'.$product->id,
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
							)) ?>
						</td>
						
	<?php if (!$product->is_available) $style='style="font-style: italic"'; else $style=''; ?>
<!--						<td <?php echo $style?>><?php echo $product->product_category ?></td> -->
						<td <?php echo $style?>><?php echo $product->brand ?></td>
						<td <?php echo $style?>><?php echo $product->reference ?></td>
						<td <?php echo $style?>><?php echo $product->caption ?></td>
						
					</tr>
<?php endforeach; ?>
				</table>
			</div>
		</div>
<?php if (!$spa) : ?>
	</div>
</div>
<?php endif;?>
		
<script id='product_script'>

// Product category
<?php echo $this->partial('/partials/show-main-script', array(
		'id' => 'product-category-anchor',
		'route' => $this->url('productCategory'),
		'script' =>'product_category_script',
		'hideForm' => true,
		'spa' => $spa,
)) ?>

// Sort on brand
<?php echo $this->partial('/partials/show-main-script', array(
		'id' => 'brand-anchor',
		'route' => $this->url('product/index').'?major=brand'.(($brand) ? '&brand='.$brand : '').(($major == 'brand' && $dir =='ASC') ? '&dir=DESC' : '&dir=ASC'),
		'script' => 'product_script',
		'hideForm' => true,
		'spa' => $spa,
)) ?>

// Sort on reference
<?php echo $this->partial('/partials/show-main-script', array(
		'id' => 'reference-anchor',
		'route' => $this->url('product/index').'?major=reference'.(($brand) ? '&brand='.$brand : '').(($major == 'reference' && $dir =='ASC') ? '&dir=DESC' : '&dir=ASC'),
		'script' => 'product_script',
		'hideForm' => true,
		'spa' => $spa,
)) ?>

// Sort on caption
<?php echo $this->partial('/partials/show-main-script', array(
		'id' => 'caption-anchor',
		'route' => $this->url('product/index').'?major=caption'.(($brand) ? '&brand='.$brand : '').(($major == 'caption' && $dir =='ASC') ? '&dir=DESC' : '&dir=ASC'),
		'script' => 'product_script',
		'hideForm' => true,
		'spa' => $spa,
)) ?>

// Add
<?php echo $this->partial('/partials/show-form-script', array(
		'id' => 'add-anchor',
		'route' => $this->url('product/update', array('product_category_id' => $product_category_id)),
		'script' =>'product_update_script',
		'spa' => $spa,
)) ?>

<?php foreach ($products as $product) : ?>

// Update
	<?php echo $this->partial('/partials/show-form-script', array(
			'id' => 'update-anchor-'.$product->id,
			'route' => $this->url('product/update', array('product_category_id' => $product_category_id, 'id' => $product->id)),
			'script' =>'product_update_script',
			'spa' => $spa,
	)) ?>


// Detail
	<?php /*echo $this->partial('/partials/show-form-script', array(
			'id' => 'detail-anchor-'.$product->id,
			'route' => $this->url('product/detail', array('product_category_id' => $product_category_id, 'id' => $product->id)),
			'script' =>'product_detail_script',
			'spa' => $spa,
	))*/ ?>
	
// Delete
	<?php echo $this->partial('/partials/show-form-script', array(
			'id' => 'delete-anchor-'.$product->id,
			'route' => $this->url('product/delete', array('id' => $product->id)),
			'script' =>'product_delete_script',
			'spa' => $spa,
	)) ?>

// Users
	<?php echo $this->partial('/partials/show-main-script', array(
			'id' => 'option-anchor-'.$product->id,
			'route' => $this->url('productOption/index', array('product_id' => $product->id)),
			'script' =>'product_option_script',
			'menuCurrent' => 'product',
			'hideForm' => true,
			'spa' => $spa,
	)) ?>

<?php endforeach;?>

</script>
