<?php
	$title = $this->translate('Catalogue: Dependencies & exclusions', 'ppit-master-data', $currentUser->locale);
    echo $this->partial('/partials/menu');
?>
<?php $this->headTitle($title); ?>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
		<div class="panel panel-default">
            <div class="panel-heading">
				<strong><?php echo $this->translate('Catalogue: Dependencies & exclusions', 'ppit-master-data', $currentUser->locale);?></strong>
            </div>
           	<div class="panel-body">
				
<!-- Form opening tag -->
				<form action="<?php echo $this->url('product/matrix', array('id' => $id)) ?>" method="post" name="product" class="form-horizontal" enctype="form-data" id="reportRow" onSubmit="return checkForm()">

<!--  CSRF -->
<?php $element = $csrfForm->get('csrf') ?>
				    <div class="form-group">
						<?php echo $this->formElement($element) ?>
<?php if ($this->formElementErrors($element)) : ?>
						<div class="col-sm-12"><p class="help-block"><?php echo $this->translate('The form has expired, please input again', 'ppit-core', $currentUser->locale) ?></p></div>
<?php endif;?>
					</div>
	
					<table class="table-condensed">
						<tr>
							<td colspan="2">
								<a href="<?php echo $this->url('product')?>">
								<strong><?php echo $this->translate('Return to products', 'ppit-master-data', $currentUser->locale) ?></strong>
								<img height="12" src="<?php echo $this->basePath('images/return.png') ?>" title="<?php echo $this->translate('Return', 'ppit-core', $currentUser->locale) ?>" alt="<?php echo $this->translate('Return', 'ppit-core', $currentUser->locale) ?>" /></a>
							</td>
						</tr>
						<tr><td colspan="2">&nbsp;</td></tr>
					
<!--  Dependance matrix -->
						<tr><td colspan="2"><strong><?php echo $this->translate('Dependence matrix', 'ppit-master-data', $currentUser->locale) ?></strong></td></tr>
					</table>

					<table class="table">
						<tr>
							<td>&nbsp;</td>
<?php $rowNum = 0; foreach ($matrix as $row_id => $row) : ?>
	<?php $rowNum++; ?>
							<td align="center"><?php echo '('.$rowNum.')' ?></td>
<?php endforeach; ?>
						</tr>

<?php $rowNum = 0; foreach ($matrix as $row_id => $row) : ?>
						<tr>
	<?php $rowNum++; $option = $productOptionTable->get($row_id, $currentUser); ?>
							<td><?php echo $option->caption.' ('.$rowNum.')' ?></td>
	<?php foreach ($row as $col_id => $constraint) : ?>
		<?php if ($row_id == $col_id) : ?>
							<td>&nbsp;</td>
		<?php else : ?>
							<td align="center">
								<input 	type="checkbox" name="<?php echo 'dep_'.$row_id.'_'.$col_id ?>" id="<?php echo 'dep_'.$row_id.'_'.$col_id ?>" onchange="update_<?php echo 'dep_'.$row_id.'_'.$col_id ?>&#x28;&#x29;"
										class="form-control" value="1"
										<?php if ($constraint == 1) echo 'checked="checked"';?>>
							</td>
		<?php endif; ?>
	<?php endforeach;?>
						</tr>
<?php endforeach; ?>

						<tr><td colspan="<?php echo $rowNum+1?>">&nbsp;</td></tr>
					</table>
						
<!--  Exclusion matrix -->
					<table class="table-condensed">
						<tr><td colspan="2"><strong><?php echo $this->translate('Exclusion matrix', 'ppit-master-data', $currentUser->locale) ?></strong></td></tr>
					</table>

					<table class="table">
						<tr>
							<td>&nbsp;</td>
<?php $rowNum = 0; foreach ($matrix as $row_id => $row) : ?>
	<?php $rowNum++; ?>
							<td align="center"><?php echo '('.$rowNum.')' ?></td>
<?php endforeach; ?>
						</tr>

<?php $rowNum = 0; foreach ($matrix as $row_id => $row) : ?>
						<tr>
	<?php $rowNum++; $option = $productOptionTable->get($row_id, $currentUser); ?>
							<td><?php echo $option->caption.' ('.$rowNum.')' ?></td>
	<?php foreach ($row as $col_id => $constraint) : ?>
		<?php if ($row_id == $col_id) : ?>
							<td>&nbsp;</td>
		<?php else : ?>
							<td align="center">
								<input 	type="checkbox" name="<?php echo 'exc_'.$row_id.'_'.$col_id ?>" id="<?php echo 'exc_'.$row_id.'_'.$col_id ?>" onchange="update_<?php echo 'exc_'.$row_id.'_'.$col_id ?>&#x28;&#x29;"
										class="form-control" value="1"
										<?php if ($constraint == 2) echo 'checked="checked"';?>>
							</td>
		<?php endif; ?>
	<?php endforeach;?>
						</tr>
<?php endforeach; ?>
					</table>

<!-- Submit button -->
				    <div class="form-group">
						<div class="col-sm-4">&nbsp;</div>
						<div class="col-sm-8">
							<input name="submit" type="submit" id="submitbutton" class="btn btn-primary" value="<?php echo $this->translate('Update', 'ppit-core', $currentUser->locale) ?>">
							&nbsp;&nbsp;
							<a href="<?php echo $this->url('product') ?>"><?php echo $this->translate('Cancel', 'ppit-core', $currentUser->locale) ?></a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<script>
<?php foreach ($matrix as $row_id => $row) : ?>
	<?php foreach ($row as $col_id => $constraint) : ?>
		<?php if ($row_id != $col_id) : ?>
function update_dep_<?php echo $row_id ?>_<?php echo $col_id ?>() {
	if (document.getElementById("dep_<?php echo $row_id ?>_<?php echo $col_id ?>").checked) {
		document.getElementById("dep_<?php echo $col_id ?>_<?php echo $row_id ?>").checked = false;
		document.getElementById("exc_<?php echo $row_id ?>_<?php echo $col_id ?>").checked = false;
		document.getElementById("exc_<?php echo $col_id ?>_<?php echo $row_id ?>").checked = false;
	}
}

function update_exc_<?php echo $row_id ?>_<?php echo $col_id ?>() {
	if (document.getElementById("exc_<?php echo $row_id ?>_<?php echo $col_id ?>").checked) {
		document.getElementById("exc_<?php echo $col_id ?>_<?php echo $row_id ?>").checked = true;
		document.getElementById("dep_<?php echo $row_id ?>_<?php echo $col_id ?>").checked = false;
		document.getElementById("dep_<?php echo $col_id ?>_<?php echo $row_id ?>").checked = false;
	}
	else if (!document.getElementById("exc_<?php echo $row_id ?>_<?php echo $col_id ?>").checked) {
		document.getElementById("exc_<?php echo $col_id ?>_<?php echo $row_id ?>").checked = false;
	}
}
		<?php endif;?>
	<?php endforeach;?>
<?php endforeach;?>
</script>
