<?php
$spa = $context->isSpaMode();
$anchorStyle = ($spa) ? $context->getAnchorStyle() : 'classic';
$current = 'product';
?>

<!-- Display header on MPA mode -->
<?php if (!$spa) : ?>
	<?php 
		$this->current = 'product';
		echo $this->partial('/partials/menu'); 
	?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
<?php endif;?>

		<div class="panel panel-default">
            <div class="panel-heading">
				<?php echo $this->translate('Update a product', 'ppit-master-data', $context->getLocale());?>: <?php echo $product->product_category->caption ?>
 				<div class="btn-group pull-right">
					<?php echo $this->partial('/partials/anchor-widget.phtml', array(
							'glyphicon' => 'glyphicon-remove',
							'title' => $this->translate('Return to list', 'ppit-core', $context->getLocale()),
							'id' => 'remove-anchor',
							'anchorStyle' => $anchorStyle,
							'spa' => $spa,
					)) ?>
				</div>
			</div>
           	<div class="panel-body">

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
			'id' => $id,
			'update_time' => $product->update_time,
			'message' => $message,
			'error' => $error,
			'csrfForm' => $csrfForm,
			'context' => $context,
)) ?>

<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>

<!-- Brand -->
<?php
	echo $this->partial('/partials/input-widget.phtml', array(
		'property' => 'brand',
		'label' => '* '.$this->translate('Brand', 'ppit-master-data', $context->getLocale()),
		'value' => $product->brand,
		'isMandatory' => true,
		'maxLength' => 255,
		'context' => $context,
		'isDisabled' => $isDisabled,
)); ?>

<!-- Reference -->
<?php
	echo $this->partial('/partials/input-widget.phtml', array(
		'property' => 'reference',
		'label' => $this->translate('Reference', 'ppit-master-data', $context->getLocale()),
		'value' => $product->reference,
		'isMandatory' => false,
		'maxLength' => 255,
		'context' => $context,
		'isDisabled' => $isDisabled,
)); ?>

<!-- Caption -->
<?php
	echo $this->partial('/partials/input-widget.phtml', array(
		'property' => 'caption',
		'label' => '* '.$this->translate('Caption', 'ppit-core', $context->getLocale()),
		'value' => $product->caption,
		'isMandatory' => true,
		'maxLength' => 255,
		'context' => $context,
		'isDisabled' => $isDisabled,
)); ?>
					
<!-- Description -->
<?php echo $this->partial('/partials/textarea-widget.phtml', array(
		'property' => 'description',
		'label' => $this->translate('Description', 'ppit-core', $context->getLocale()),
		'rows' => 3, 
		'value' => $product->description,
		'isMandatory' => false,
		'maxLength' => 2047,
		'context' => $context,
		'isDisabled' => $isDisabled,
)); ?>
					
<!-- Available ? -->
<?php
	echo $this->partial('/partials/checkbox-widget.phtml', array(
		'property' => 'is_available',
		'label' => $this->translate('Available ?', 'ppit-master-data', $context->getLocale()),
		'value' => $product->is_available,
		'context' => $context,
		'isDisabled' => $isDisabled,
)); ?>

<!-- Properties -->
<?php foreach ($product->product_category->properties as $property => $definition) : ?>
	<?php echo $this->partial('/partials/dynamic-widget.phtml', array(
			'property' => $property,
			'definition' => $definition,
			'collection' => $product->properties,
			'context' => $context,
			'isDisabled' => $isDisabled,
	)); ?>
<?php endforeach;?>

<!-- Prices -->
<div class="form-group">
	<label class="col-sm-5 control-label"><?php echo $this->translate('Price', 'ppit-master-data', $context->getLocale()) ?>:</label>
	<div class="col-sm-7">&nbsp;</div>
</div>
<?php foreach ($config['ppitMasterDataSettings']['priceCategories'] as $category => $caption) : ?>
	<?php echo $this->partial('/partials/number-widget.phtml', array(
			'property' => 'price_'.$category,
			'label' => '* '.$caption,
			'value' => $product->prices[$category],
			'isMandatory' => true,
			'min' => 0.01,
			'max' => 999999,
			'context' => $context,
			'isDisabled' => $isDisabled,
	)); ?>
<?php endforeach;?>

<!-- Form footer -->
<?php echo $this->partial('/partials/form-footer') ?>

			</div>
		</div>
<?php if (!$spa) : ?>
	</div>
</div>
<?php endif;?>

<!-- Load the common form javascript functions -->
<?php echo $this->partial('/partials/common-form-js.phtml'); ?>

<script id="product_update_script">

// Close form
<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'remove-anchor',
		'route' => $this->url('product/index', array('product_category_id' => $product->product_category_id)),
		'spa' => $spa,
)) ?>

<?php if ($message == 'OK') : ?>

<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'foot-return-anchor',
		'route' => $this->url('product/index', array('product_category_id' => $product->product_category_id)),
		'spa' => $spa,
)) ?>

<?php else : ?>

<?php echo $this->partial('/partials/form-return-script', array(
		'id' => 'cancel-anchor',
		'route' => $this->url('product/index', array('product_category_id' => $product->product_category_id)),
		'spa' => $spa,
)) ?>

// Submit
<?php
$properties = array(
		'brand' => 'input',
		'reference' => 'input',
		'caption' => 'input',
		'description' => 'input',
		'is_available' => 'checkbox',
		'price' => 'input',
		'update_time' => 'hidden',
);
// Add dynamic properties
foreach ($product->product_category->properties as $property => $definition) {
	$properties['property_'.$property] = $definition['type'];
}
// Add prices
foreach ($config['ppitMasterDataSettings']['priceCategories'] as $category => $caption) {
	$properties['price_'.$category] = 'input';
}
echo $this->partial('/partials/form-button-script', array(
		'context' => $context,
		'id' => 'submit-button',
		'checkFunction' => 'checkForm',
		'formRoute' => $this->url('product/update', array('product_category_id' => $product->product_category_id, 'id' => $id)),
		'formScript' =>'product_update_script',
		'properties' => $properties,
		'mainRoute' => $this->url('product/index', array('product_category-id' => $product->product_category_id)),
		'mainScript' =>'product_script',
		'hideForm' => false,
)) ?>

<?php endif;?>

// The elements are checked last to first so the focus is positionned on the first element on error
function checkForm() 
{
	var validity = true;	

// Prices
<?php foreach ($config['ppitMasterDataSettings']['priceCategories'] as $category => $caption) : ?>
	if (!check_price_<?php echo $category ?>()) validity = false;
<?php endforeach;?>

// Properties
<?php foreach ($product->product_category->properties as $property => $definition) : ?>
	if (!check_property_<?php echo $property ?>()) validity = false;
<?php endforeach;?>

// Description
if (!check_description()) validity = false;

// Caption
if (!check_caption()) validity = false;

// Reference
if (!check_reference()) validity = false;

// Brand
if (!check_brand()) validity = false;

	return validity;
}
</script>
  