<?php
$spa = true;
$anchorStyle = ($spa) ? $context->getAnchorStyle() : 'classic';
$current = 'product';
?>

<!-- Display header on MPA mode -->
<?php if (!$spa) : ?>
	<?php 
		$this->current = 'product';
		echo $this->partial('/partials/menu'); 
	?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
<?php endif;?>

		<div class="panel panel-default">
            <div class="panel-heading">
				<?php echo $this->translate('Product categories', 'ppit-master-data', $context->getLocale()) ?>
            </div>
           	<div class="panel-body">
				<table class="table table-striped">
					<tr>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td>&nbsp;</td>
						<td><strong>
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'text' => $this->translate('Caption', 'ppit-core', $context->getLocale()),
									'id' => 'caption-anchor',
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
							)) ?>
						</strong></td>
					</tr>
					<tr>
						<td colspan="6">
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'glyphicon' => 'glyphicon-plus',
									'title' => $this->translate('Add', 'ppit-core', $context->getLocale()),
									'id' => 'add-anchor',
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
							)) ?>
						</td>
					</tr>
<?php foreach ($productCategories as $productCategory) : ?>
					<tr>
						<td>
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'glyphicon' => 'glyphicon-edit',
									'title' => $this->translate('Update', 'ppit-core', $context->getLocale()),
									'id' => 'update-anchor-'.$productCategory->id,
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
							)) ?>
						</td>
						<td>
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'glyphicon' => 'glyphicon-trash',
									'title' => $this->translate('Delete', 'ppit-core', $context->getLocale()),
									'id' => 'delete-anchor-'.$productCategory->id,
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
									'disabled' => !$productCategory->isDeletable(),
							)) ?>
						</td>
						<td>
							<?php echo $this->partial('/partials/anchor-widget.phtml', array(
									'text' => $this->translate('Products', 'ppit-master-data', $context->getLocale()),
									'id' => 'product-anchor-'.$productCategory->id,
									'anchorStyle' => $context->getAnchorStyle(),
									'spa' => $spa,
							)) ?>
						</td>
						<td><?php echo $productCategory->caption ?></td>
					</tr>
<?php endforeach; ?>
				</table>
			</div>
		</div>
<?php if (!$spa) : ?>
	</div>
</div>
<?php endif;?>
		
<script id='product_category_script'>

// Sort on caption
<?php echo $this->partial('/partials/show-main-script', array(
		'id' => 'caption-anchor',
		'route' => $this->url('productCategory/index').'?major=caption'.(($major == 'caption' && $dir =='ASC') ? '&dir=DESC' : '&dir=ASC'),
		'script' => 'product_category_script',
		'hideForm' => true,
		'spa' => $spa,
)) ?>

// Add
<?php echo $this->partial('/partials/show-form-script', array(
		'id' => 'add-anchor',
		'route' => $this->url('productCategory/update'),
		'script' =>'product_category_update_script',
		'spa' => $spa,
)) ?>

<?php foreach ($productCategories as $productCategory) : ?>

// Update
	<?php echo $this->partial('/partials/show-form-script', array(
			'id' => 'update-anchor-'.$productCategory->id,
			'route' => $this->url('productCategory/update', array('id' => $productCategory->id)),
			'script' =>'product_category_update_script',
			'spa' => $spa,
	)) ?>
	
// Delete
	<?php echo $this->partial('/partials/show-form-script', array(
			'id' => 'delete-anchor-'.$productCategory->id,
			'route' => $this->url('productCategory/delete', array('id' => $productCategory->id)),
			'script' =>'product_category_delete_script',
			'spa' => $spa,
	)) ?>

// Users
	<?php echo $this->partial('/partials/show-main-script', array(
			'id' => 'product-anchor-'.$productCategory->id,
			'route' => $this->url('product/index', array('product_category_id' => $productCategory->id)),
			'script' =>'product_script',
			'menuCurrent' => 'product',
			'hideForm' => true,
			'spa' => $spa,
	)) ?>

<?php endforeach;?>

</script>
