<?php
$spa = true;
$anchorStyle = ($spa) ? $context->getAnchorStyle() : 'classic';
?>

<!-- Display header on MPA mode -->
<?php if (!$spa) : ?>
	<?php 
		$this->current = 'admin';
		echo $this->partial('/partials/menu'); 
	?>
<?php endif;?>

<h4><?php echo $this->translate('Add an access control', 'ppit-master-data', $context->getLocale()) ?></h4>

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
			'formId' => 'org-unit-contact-add-form',
			'update_time' => $orgUnitContact->update_time,
			'message' => $message,
			'error' => $error,
			'csrfForm' => $csrfForm,
			'context' => $context,
)) ?>

<?php if ($message == 'OK' || !$context->isAllowed('orgUnitContact/add')) $isDisabled = true; else $isDisabled = false; ?>

<!-- Contact -->
<?php
	echo $this->partial('/partials/input-widget.phtml', array(
		'property' => 'name',
		'label' => '* '.$this->translate('Agent', 'ppit-master-data', $context->getLocale()),
		'value' => $orgUnitContact->n_fn,
		'isMandatory' => true,
		'context' => $context,
		'isDisabled' => $isDisabled,
)); ?>
<input type="hidden" id="contact_id" name="contact_id" />

<!-- Role -->
<?php
/*	$roles = array();
	foreach ($orgUnitContact->getRoles() as $role_id => $role_caption) $roles[$role_id] = $this->translate($role_caption, 'ppit-master-data', $context->getLocale());
	echo $this->partial('/partials/select-widget.phtml', array(
		'property' => 'role_id',
		'label' => '* '.$this->translate('Role', 'ppit-master-data', $context->getLocale()),
		'modalities' => $roles,
		'value' => $orgUnitContact->role_id,
		'isMandatory' => true,
		'context' => $context,
		'isDisabled' => $isDisabled,
));*/ ?>

<!-- Effect -->
<?php echo $this->partial('/partials/date-widget.phtml', array(
		'property' => 'effect',
		'label' => $this->translate('Effective date', 'ppit-master-data', $context->getLocale()),
		'value' => $orgUnitContact->effect,
		'isMandatory' => false,
		'minDate' => '0000-00-00',
		'maxDate' => '9999-99-99',
		'context' => $context,
		'isDisabled' => $isDisabled,
)); ?>

<!-- Form footer -->
<?php echo $this->partial('/partials/form-footer', array(
	'prefix' => 'org_unit_contact_',
	'class' => 'btn-danger',
	'message' => $message,
	'context' => $context,
)) ?>

<!-- Load the common form javascript functions -->
<?php echo $this->partial('/partials/common-form-js.phtml'); ?>

<script id='org_unit_contact_add_script'>

$('#name').autocomplete({
	source : function(request, response){
    $.ajax({
    		url : '<?php echo $this->url('vcard/listRest') ?>', // Server request returning json data
            dataType : 'json', // The data type is json
            data : {
                filter : $('#name').val(), // Giving the prefix (at least 3 chars input)
                maxRows : 15
            },
            
            success : function(donnee){
	            	response($.map(donnee.data, function(object){
        			document.getElementById("contact_id").value = object.id;
	            	return object.label;
                }));
            }
        });
    }
});

<?php if ($message == 'OK') : ?>

	$('#org_unit_contact_foot-return-anchor').click(function () {
		reload(
			'<?php echo $this->url('orgUnitContact/list', array('org_unit_id' => $org_unit_id)) ?>',
			'org_unit_contact_list_script',
			'org_unit_contact_list'
		);
	} );

<?php else : ?>

	$('#org_unit_contact_cancel-anchor').click(function () {
		reload(
			'<?php echo $this->url('orgUnitContact/list', array('org_unit_id' => $org_unit_id)) ?>',
			'org_unit_contact_list_script',
			'org_unit_contact_list'
		);
	} );

	// Submit
	<?php
	$properties = array('contact_id' => 'hidden'/*, 'role_id' => 'input'*/, 'effect' => 'input', 'update_time' => 'hidden');
	echo $this->partial('/partials/form-button-script', array(
			'context' => $context,
			'formId' => 'org-unit-contact-add-form',
			'id' => 'submit-button',
			'checkFunction' => 'checkForm',
			'formRoute' => $this->url('orgUnitContact/add', array('org_unit_id' => $org_unit_id, 'id' => $id)),
			'formScript' => 'org_unit_contact_add_script',
			'target' => 'org_unit_contact_list',
			'properties' => $properties,
			'mainRoute' => null,
			'hideForm' => false,
	)) ?>
	
	function checkForm() {
		validity = true;
		if (!check_effect()) validity = false;
//		if (!check_role_id()) validity = false;
		if (document.getElementById('contact_id').value == '') {
			validity = false;
			renderElement('name', '<?php echo $this->translate('Please select a contact', 'ppit-contact', $context->getLocale()) ?>')
		}
		return validity;
	}

<?php endif;?>

</script>
