<?php
$spa = true;
$anchorStyle = ($spa) ? $context->getAnchorStyle() : 'classic';
?>

<!-- Display header on MPA mode -->
<?php if (!$spa) : ?>
	<?php 
		$this->current = 'admin';
		echo $this->partial('/partials/menu'); 
	?>
<?php endif;?>

<h4><?php echo $this->translate('Delete an access control', 'ppit-master-data', $context->getLocale()) ?></h4>

<table class="table-condensed">
	<tr>
		<td class="ppit-header-caption"><?php echo $this->translate('Agent', 'ppit-master-data', $context->getLocale())?></td>
		<td><?php echo $orgUnitContact->n_fn ?>
	</tr>
	<tr>
		<td class="ppit-header-caption"><?php echo $this->translate('Effective date', 'ppit-master-data', $context->getLocale())?></td>
		<td><?php echo $context->decodeDate($orgUnitContact->effect) ?>
	</tr>
</table>

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
	'formId' => 'org-unit-contact-delete-form',
	'update_time' => $orgUnitContact->update_time,
	'message' => $message,
	'error' => $error,
	'csrfForm' => $csrfForm,
	'context' => $context,
)) ?>

<!-- Form footer -->
<?php echo $this->partial('/partials/form-footer', array(
	'prefix' => 'org_unit_contact_',
	'class' => 'btn-danger',
	'message' => $message,
	'context' => $context,
)) ?>

			</div>
		</div>

<script id='org_unit_contact_delete_script'>

<?php if ($message == 'OK') : ?>

	$('#org_unit_contact_foot-return-anchor').click(function () {
		reload(
			'<?php echo $this->url('orgUnitContact/list', array('org_unit_id' => $orgUnitContact->org_unit_id)) ?>',
			'org_unit_contact_list_script',
			'org_unit_contact_list'
		);
	} );

<?php else : ?>

	$('#org_unit_contact_cancel-anchor').click(function () {
		reload(
			'<?php echo $this->url('orgUnitContact/list', array('org_unit_id' => $orgUnitContact->org_unit_id)) ?>',
			'org_unit_contact_list_script',
			'org_unit_contact_list'
		);
	} );

// Submit
	<?php echo $this->partial('/partials/form-button-script', array(
			'context' => $context,
			'formId' => 'org-unit-contact-delete-form',
			'id' => 'submit-button',
			'formRoute' => $this->url('orgUnitContact/delete', array('id' => $id)),
			'formScript' =>'org_unit_contact_delete_script',
			'target' => 'org_unit_contact_list',
			'properties' => array('update_time' => 'hidden'),
			'mainRoute' => null,
			'hideForm' => false,
	)) ?>

<?php endif;?>

</script>

